---
hostname: z9100-01
# ansible_ssh_user: admin
# ansible_ssh_pass: force10
ansible_become: yes
ansible_connection: ansible.netcommon.network_cli
#ansible_network_os: dellemc.os10.os10
ansible_network_os: dellemc.enterprise_sonic.sonic

# Additional parameters for connection type httpapi:
#ansible_httpapi_use_ssl: true
ansible_httpapi_use_ssl: fasle
ansible_httpapi_validate_certs: false



